- name: Download google chrome .deb installer
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-installer.deb
    
- name: Install google chrome 
  apt:
    deb: /tmp/google-installer.deb
  become: true