---
  - name: Installing development environment
    hosts: all
    vars:
      remote_user: "{{ lookup('env', 'USER') }}"
      action: install
      add_ssh_pkeys: false
      sym_links: false
    roles:
      - i3-gaps
      - { role: ssh, when: add_ssh_pkeys|bool == true }
      - utilities
      - system-settings
      - sublime
      - fzf
      - vscode
      - docker
      - docker-compose
      - google-chrome
      - firefox
      - node
      - libreoffice
      - vlc
      - openfortigui
      - zoom
      - silversearcher-ag
      - pulseaudio
      - ansible
      - pycharm
      - slack
      - outlook
      - keepass
      - dropbox
      - themes
      - { role: symbolic-link, when: sym_links|bool == true }
