---
#  - name: Install i3
#    hosts: all
#    become: yes
#    vars_files:
#      - vars/defaults.yml
#      - vars/vars.yml
#    roles:
#      - i3
#      - themes
#      - utilities
#

  - name: This is a hello-world example
    hosts: vagrant
    become: true

    vars_files:
      - vars/defaults.yml
      - vars/vars.yml
    tasks:
      - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
        copy:
          content: hello worldn
          dest: /tmp/testfile.txt