---
- name: Add keepass repositories
  apt_repository:
    repo: "{{ keepass_apt_repo }}"
    state: present
    update_cache: no
    validate_certs: no
  become: true

- name: Install keepass (ensure downloading DB from dropbox)
  apt: pkg={{item}} update_cache=false force=yes state=present
  with_items:
   - keepass2
  become: true
