---
sublime_apt_repo: "deb https://download.sublimetext.com/ apt/stable/"

sublime_apt_key: https://download.sublimetext.com/sublimehq-pub.gpg

sublime_config_path: "/home/{{remote_user}}/.config"
sublime_package_path: "{{ sublime_config_path }}/sublime-text-3/Installed Packages"
