---

- name: ensure sublime text is removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages:
      - sublime-text

- name: ensure sublime text repo is removed
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_state: absent
    apt_repo_keys:
      - "{{ sublime_apt_key }}"
    apt_repo_repositories:
      - "{{ sublime_apt_repo }}"
