---
- name: Ensure system dotfiles settings
  copy: src={{item}} dest=/home/{{remote_user}} owner={{remote_user}} group={{remote_user}} mode='u=rw' force=yes   
  with_fileglob:
    - bash_history/.*
    - bashrc/.*
    - dsh/.*
    - gitconfig/.*
    - git_prompt_custom/.*
    - javi/.*
    - psqlrc/.*
    - vimrc/.*
    - xinitrc/.*
    - inputrc/.*

- name: Ensure we have keyboard es in .profile
  ansible.builtin.lineinfile:
    path: /home/{{remote_user}}/.profile    
    line: 'setxkbmap -layout es'
    insertafter: EOF