---
- name: Ensure system dotfiles settings
  copy: src={{item}} dest=/home/{{remote_user}} owner={{remote_user}} group={{remote_user}} mode='u=rw' force=yes   
  with_fileglob:
    - bash_history/.*
    - bashrc/.*
    - dsh/.*
    - gitconfig/.*
    - git_prompt_custom/.*
    - javi/.*
    - psqlrc/.*
    - vimrc/.*
    - xinitrc/.*

