---
- name: Ensure system dotfiles settings
  copy: src={{item}} dest=/home/{{remote_user}} owner={{remote_user}} group={{remote_user}} mode='u=rw' force=yes   
  with_fileglob:
    - bash_history/.*
    - bashrc/.*
    - gitconfig/.*
    - git_prompt_custom/.*
    - javi/.*
    - psqlrc/.*
    - vimrc/.*
    - xinitrc/.*
    - inputrc/.*

- name: Ensure we have keyboard es in .profile
  lineinfile:
    path: /home/{{remote_user}}/.profile    
    line: 'setxkbmap -layout es'
    insertafter: EOF

- name: Install dsh
  apt: pkg={{item}} update_cache=true force=yes state=present
  with_items:
   - dsh

- name: Create dsh directory if it does not exist
  file:
    path: /home/{{remote_user}}/.dsh
    state: directory
    mode: '0755'

- name: Create dsh group if it does not exist
  file:
    path: /home/{{remote_user}}/.dsh/group
    state: directory
    mode: '0755'

- name: Create dsh config if it does not exist
  file:
    path: /home/{{remote_user}}/.dsh/config
    state: directory
    mode: '0755'

- name: Ensure dsh config settings
  copy: src={{item}} dest=/home/{{remote_user}}/.dsh owner={{remote_user}} group={{remote_user}} mode='u=rw' force=yes   
  with_fileglob:
    - dsh/dsh.conf

- name: Create .javirc if it does not exist
  file:
    path: /home/{{remote_user}}/.javirc
    state: touch

- name: Write eval ssh to javirc
  command: "{{ item }}"  
  with_items:
    - echo 'eval $(keychain --eval --agents ssh id_rsa)' >> /home/{{remote_user}}/.javirc
  become: true