---
- name: Ensure fzf is cloned
  git:
    repo: "{{ fzf_git_url }}"
    dest: "{{ fzf_git_path }}"
    clone: True
    force: True
    recursive: True
    update: True
    depth: 1

- name: fzf - install 
  command: "{{ item }}"
  args:
    chdir: "{{ fzf_git_path }}"
  with_items:
    - su {{remote_user}} -c 'bash /home/{{remote_user}}/.fzf/install --all'
  
