---
- name: Ensure fzf is cloned
  git:
    repo: "{{ fzf_git_url }}"
    dest: "{{ fzf_git_path }}"
    clone: True
    force: True
    recursive: True
    update: True
    depth: 1
  become: true

- name: fzf - install 
  ansible.builtin.script:
    cmd: /home/{{remote_user}}/.fzf/install --all