---
- name: Ensure wallpapers folder exists
  file:
    path: "{{wallpapers_path}}"
    state: directory
    mode: 0755

- name: Copy all wallpapers 
  copy: src={{item}} dest=/home/{{remote_user}}/.wallpapers/ owner={{remote_user}} group={{remote_user}} mode='u=rw'
  with_fileglob:
    - wallpapers/*

- name: Install fonts
  apt: pkg={{item}} update_cache=true force=yes state=present
  with_items:
   - fonts-noto-color-emoji
   - fonts-font-awesome
   - fonts-google
   - fonts-dejavu
   - fonts-roboto
  become: true
