---
# Uninstall all theme releated packages and configs

- name: Install fonts
  apt: pkg={{item}} update_cache=true force=yes state=absent
  with_items:
   - fonts-noto-color-emoji
   - fonts-noto-color-emoji
   - fonts-font-awesome
   - fonts-google
   - fonts-dejavu
   - fonts-roboto
