---

- name: Remove docker 
  apt: pkg={{item}} force=yes state=absent
  with_items:
    - docker-ce

- name: Remove docker repositories
  apt_repository: repo='{{item}}' state=absent
  with_items:
    - "{{ docker_apt_repo }}"
