---
- name: Ensure dependencies are installed
  apt:
    update_cache: true
    force: yes
    state: present
    name: "{{ utilities_dependencies }}"
  become: true


- name: Ensure alacritty config files
  copy: src={{item}} dest=/home/{{remote_user}}/.config/alacritty/ owner={{remote_user}} group={{remote_user}} mode='u=rw'
  with_fileglob:
   - alacritty/*

- name: Ensure wofi config files
  copy: src={{item}} dest=/home/{{remote_user}}/.config/wofi/ owner={{remote_user}} group={{remote_user}} mode='u=rw'
  with_fileglob:
   - wofi/*