---
- name: Ensure dependencies are installed
  apt:
    update_cache: true
    force: yes
    state: present
    name: "{{ utilities_dependencies }}"
  become: true

- name: Download vagrant package
  get_url:
    url: https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
    dest: /tmp/vagrant-installer.deb
    
- name: Install vagrant chrome 
  apt:
    deb: /tmp/vagrant-installer.deb
  become: true