---

- name: ensure docker is removed
  vars:
    apt_state: absent
    apt_packages: "{{ [docker_package_name] }}"

- name: ensure docker repo is removed
  vars:
    apt_repo_state: absent
    apt_repo_keys:
      - "{{ docker_apt_key }}"
    apt_repo_repositories:
      - "{{ docker_apt_repo }}"
