---
utilities_dependencies:
  - autorandr
  - x11-xserver-utils # xrandr
  - feh
  - xautolock
  - imagemagick # adds mogrify
  - nmap
  - locate
  - vim
  - virtualbox
  - htop
  - pavucontrol
  - openvpn
  - net-tools
  - keychain
  #- ipython


